# install apache and php

---
  - hosts: loadbalancers
    become: true
    tasks: 
      - name: Install apache
        yum: name=httpd state=present
      - name: Ensure Apache starts
        service: name=httpd state=started enabled=yes

  - hosts: webservers
    become: true
    tasks: 
      - name: Install services
        yum: 
          name:
            - httpd 
            - php
          state: present
      - name: Ensure Apache starts
        service: name=httpd state=started enabled=yes