# setup-app.yml

---
  - hosts: webservers
    become: true
    tasks:
      - name: upload application files 
        copy: 
          src: ../index.php
          dest: /var/www/html
          mode: 0755

      - name: Config php.ini file
        lineinfile:
          path: /etc/php.ini
          regexp: ^short_open_tag
          line: 'short_open_tag=on'

      - name: restart apache
        service: name=httpd state=restarted